name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MATLAB_CMD: /home/runner/work/_actions/matlab-actions/run-tests/v3/dist/bin/glnxa64/run-matlab-command
    steps:
      - uses: actions/checkout@v6
      - uses: matlab-actions/setup-matlab@v3
        with:
          cache: true
      - uses: matlab-actions/run-tests@v3
      - name: Warm up MATLAB TOML server
        run: echo 'key = "value"' | ./ci.bash "${{ env.MATLAB_CMD }}"
      - uses: watermarkhu/toml-test-action@main
        with:
          command: ./ci.bash ${{ env.MATLAB_CMD }}
          skip: "invalid/encoding/bad-utf8-*"
          parallel: 1
          timeout: 10s
