name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MATLAB_CMD: /home/runner/work/_actions/matlab-actions/run-tests/v3/dist/bin/glnxa64/run-matlab-command
    steps:
      - uses: actions/checkout@v6
      - uses: matlab-actions/setup-matlab@v3
        with:
          cache: true
      - uses: matlab-actions/run-tests@v3
        with:
          source-folder: .
          select-by-folder: test
      - uses: actions/setup-go@v6
      - name: Install toml-test v2.1.0
        run: go install github.com/toml-lang/toml-test/v2/cmd/toml-test@v2.1.0
      - name: Warm up MATLAB TOML server
        run: echo 'key = "value"' | ./test/ci.bash "${{ env.MATLAB_CMD }}"
      - name: Run toml-test
        run: >
          toml-test test
          -decoder="./test/ci.bash ${{ env.MATLAB_CMD }}"
          -skip="invalid/encoding/bad-utf8-*"
          -parallel=1
          -timeout=10s
